# define the font
font_family Hack Nerd Font
bold_font   Hack Nerd Font
italic_font Hack Nerd Font
bold_italic_font Hack Nerd Font

# define the font size
font_size 13

# background
background #1c1c1c
# foreground #b2b2b2
# foreground #bcbcbc
foreground #c1c1c1

# black
color0   #767676
color8   #767676

# red
color1   #d78700
color9   #d78700

# green
color2   #5f8700
color10  #5f8700

# # yellow
# color3   #afaf5f
# color11  #afaf5f

# # yellow
# color3   #bfbf4f
# color11  #bfbf4f

# yellow
color3   #b7b757
color11  #b7b757

# blue
color4   #87afd7
color12  #87afd7

# magenta
color5   #875f87
color13  #875f87

# cyan
color6   #d75f5f
color14  #d75f5f

# white
color7   #b2b2b2
color15  #b2b2b2

# cursor
cursor #8a8a8a
cursor #b2b2b2

# do not use shell integration
shell_integration disabled

# window settings
hide_window_decorations no
window_margin_width 0
placement_strategy top-left

# ensure that the cells always
# take up the full space
modify_font cell_width 100%

# do not support a "bell" sound
# for certain terminal events
enable_audio_bell no

# performance settings
input_delay 0
repaint_delay 2
sync_to_monitor no
