# define the font
# - uncomment the font you want to use
# - make sure that the other fonts are
# commented out
# - see the correct font names by running
# the command:
# fc-list --format="%{family[0]}\n" | sort | uniq

# --> JetBrainsMono Nerd Font Mono

# font_family JetBrainsMono Nerd Font
# bold_font   JetBrainsMono Nerd Font
# italic_font  JetBrainsMono Nerd Font
# bold_italic_font JetBrainsMono Nerd Font

# --> MonaSpace Nerd Font Mono
# (note that the name on Nerd Fonts
# is Monaspice and the letters after
# the word "Monaspice" are the way
# to pick the different font variant)

# font_family MonaspiceAr Nerd Font Mono
# bold_font   MonaspiceAr Nerd Font Mono
# italic_font MonaspiceAr Nerd Font Mono
# bold_italic_font MonaspiceAr Nerd Font Mono

# font_family MonaspiceNe Nerd Font Mono
# bold_font   MonaspiceNe Nerd Font Mono
# italic_font MonaspiceNe Nerd Font Mono
# bold_italic_font MonaspiceNe Nerd Font Mono

# --> Maple Mono Nerd Font Mono
# (note that the use of the "Normal NF"
# version restricts the use of custom
# fonts and glyphs while the "NF"
# version offers a full feature set)

font_family Maple Mono Normal NF
bold_font   Maple Mono Normal NF
italic_font Maple Mono NF
bold_italic_font Maple Mono NF

# --> Hack Nerd Font Mono

# font_family Hack Nerd Font
# bold_font   Hack Nerd Font
# italic_font Hack Nerd Font
# bold_italic_font Hack Nerd Font

# define the font size
font_size 13

# background
background #1c1c1c
foreground #c1c1c1

# black
color0   #767676
color8   #767676

# red
color1   #d78700
color9   #d78700

# green

# color2   #5f8700
# color10  #5f8700

color2   #6f9500
color10  #6f9500

# yellow
color3   #b7b757
color11  #b7b757

# blue
color4   #87afd7
color12  #87afd7

# magenta

# color5   #875f87
# color13  #875f87

color5   #a569a5
color13  #a569a5

# cyan
color6   #d75f5f
color14  #d75f5f

# white
color7   #b2b2b2
color15  #b2b2b2

# cursor
cursor #8a8a8a
cursor #b2b2b2

# do not use shell integration
shell_integration disabled

# window settings
hide_window_decorations no
window_margin_width 0
placement_strategy top-left

# ensure that the cells always
# take up the full space
modify_font cell_width 100%

# do not support a "bell" sound
# for certain terminal events
enable_audio_bell no

# performance settings
input_delay 0
repaint_delay 2
sync_to_monitor no
