# ~/.config/starship.toml

[directory]
format = '[ $path](bold green)[$read_only]($read_only_style) '
truncation_length = 5
truncation_symbol = " "
home_symbol = "~"
read_only = " "

[git_branch]
truncation_length = 30
symbol = ' '
truncation_symbol = ' '

[lua]
format = '[ $version ](bold blue)'

[nix_shell]
disabled = false
impure_msg = '[󰄶 shell](bold blue) '
pure_msg = '[󰄸 shell](bold blue) '
unknown_msg = '[ shell](bold blue) '
format = '[󰜗 nix $state(\($name\))](bold blue) '

[package]
format = '[ $version ](bold red)'

[python]
format = '[ $version (\($virtualenv\) )](bold yellow)'

# [custom.devbox]
# format = '[󱓞 devbox](bold cyan)'
# when = """ test "$DEVBOX_SHELL_ENABLED" "==" "1" """
