[aliases]

# Substring match for wezterm
# Note that this ensures that the
# "org."-based name of wezterm is
# not displayed on the polybar
wezterm = "Wezterm"

# Substring match for Brave-browser
# to use short name and capitalization in a
# consistent fashion
Brave = "Brave"

# Substring match for firefox
# to use capitalization in a
# consistent fashion
firefox = "Firefox"

# Substring match for discord
# to use capitalization in a
# consistent fashion
discord = "Discord"

# Substring match for Kitty
# to use capitalization in a
# consistent fashion
kitty = "Kitty"
