#!/bin/sh

# This script performs a backup using rsync

echo "Free space on all of the file systems:"

df -h

echo ""

echo "Starting backup to vatomauro using rsync:"

rsync -avP --delete --exclude=.cache --exclude=.dockagator --exclude=docker /home/gkapfham gkapfham@vatomauro:/home/gkapfham/backup/
diagnostic=$?

echo ""

if [ "$diagnostic" -eq 0 ]; then
    echo "Hooray, the backup worked correctly!"
else
    echo "Oops, the backup did not work correctly!"
    echo "Make sure that you run 'sudo mount /dev/sda1 /mnt/usb/' on vatomauro"
fi

echo ""
