#!/bin/sh

# Reminder: use the command 'xrandr' to see what
# monitors are available.

xrandr --output DP1 --above eDP1 --auto

# Either command leads to connecting the
# two displays together so that the external display
# (display name like DP1) is above the laptop display
# (display name: eDP1). This means that you can move
# the cursor off the top of the laptop and onto
# the external display.
