#!/usr/bin/env python

import sys

import fitz


def main():
    input_filename = sys.argv[1]
    doc = fitz.open(input_filename)
    for i in range(doc.pageCount):
        page = doc[i]
        for annot in page.annots():
            print(annot.info["content"])

if __name__ == "__main__":
    main()
