#!/bin/bash

# Reference:
# https://blog.meain.io/2020/tmux-flating-scratch-terminal/

if [ "$(tmux display-message -p -F "#{session_name}")" = "popup" ];then
    tmux detach-client
else
    tmux popup -E "tmux attach -t popup || tmux new -s popup"
fi
